#define TORSO_WIDTH 4.0f
#define TORSO_HEIGHT 8.0f
#define TORSO_DEPTH 2.0f

#define HEAD_WIDTH 1.0f
#define HEAD_HEIGHT 1.5f
#define HEAD_DEPTH 1.0f

#define EAR_RADIUS 0.5f
#define EAR_HEIGHT 0.75f

#define UPPER_ARM_WIDTH 1.5f
#define UPPER_ARM_HEIGHT 3.0f
#define UPPER_ARM_DEPTH 1.5f

#define LOWER_ARM_WIDTH 1.0f
#define LOWER_ARM_HEIGHT 3.0f
#define LOWER_ARM_DEPTH 1.0f

#define UPPER_LEG_WIDTH 1.5f
#define UPPER_LEG_HEIGHT 4.0f
#define UPPER_LEG_DEPTH 1.5f

#define LOWER_LEG_WIDTH 1.0f
#define LOWER_LEG_HEIGHT 4.0f
#define LOWER_LEG_DEPTH 1.0f
#define MONKEY_X (LOWER_ARM_HEIGHT+UPPER_ARM_HEIGHT+TORSO_DEPTH)
#define MONKEY_Y (LOWER_LEG_HEIGHT+UPPER_LEG_HEIGHT)
